Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;

namespace RestaurantMVCUI.Controllers
{
    public class BillController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using RestaurantEntity;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace RestaurantMVCUI.Controllers
{
    public class CustomerController : Controller
    {
        private IConfiguration _configuration;

        public CustomerController(IConfiguration configuration)
        {
            _configuration = configuration;
        }


        public async Task<IActionResult> IndexAsync()
        {
            IEnumerable<Food> foodresult = null;
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApiBaseUrl"] + "Food/GetFoods";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        foodresult = JsonConvert.DeserializeObject<IEnumerable<Food>>(result);
                    }
                }
            }
            return View(foodresult);
        }
    }
}

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using RestaurantEntity;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace RestaurantMVCUI.Controllers
{

    public class OrderController : Controller
    {
        public static List<Order> orders = new List<Order>();

        
        private IConfiguration _configuration;

        public OrderController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Food> foodresult = null;
            using (HttpClient client = new HttpClient())
            {


                string endPoint = _configuration["WebApiBaseUrl"] + "Food/GetFoods";//api controller name and httppost name given inside httppost in moviecontroller of api

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {   //dynamic viewbag we can create any variable name in run time
                        var result = await response.Content.ReadAsStringAsync();
                        foodresult = JsonConvert.DeserializeObject<IEnumerable<Food>>(result);
                    }



                }
            }
            return View(foodresult);

        }
        [HttpGet]
        public async Task<IActionResult> AddOrder1(int FoodId)
        {
            Order order = new Order();
            order.FoodId = FoodId;

            Food food = null;
            using (HttpClient client = new HttpClient())
            {


                string endPoint = _configuration["WebApiBaseUrl"] + "Food/GetFoodById?foodId=" + FoodId;//movieId is apicontroleer passing argument name//api controller name and httppost name given inside httppost in moviecontroller of api

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {   //dynamic viewbag we can create any variable name in run time
                        var result = await response.Content.ReadAsStringAsync();
                        food = JsonConvert.DeserializeObject<Food>(result);
                    }



                }
            }
            TempData["foodcost1"] = Convert.ToInt32(food.FoodCost);
            TempData.Keep();
            //
            IEnumerable<HallTable> halltable = null;
            using (HttpClient client = new HttpClient())
            {


                string endPoint = _configuration["WebApiBaseUrl"] + "HallTable/GetHallTables";//api controller name and httppost name given inside httppost in moviecontroller of api

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {   //dynamic viewbag we can create any variable name in run time
                        var result = await response.Content.ReadAsStringAsync();
                        halltable = JsonConvert.DeserializeObject<IEnumerable<HallTable>>(result);
                    }



                }
            }

            List<SelectListItem> tableId = new List<SelectListItem>()
            {
                new SelectListItem{Value="Select",Text="select"},
                new SelectListItem{Value="1",Text="1"},
                new SelectListItem{Value="2",Text="2"},
                new SelectListItem{Value="3",Text="3"},

            };


            ViewBag.tablelist = tableId;


            return View(order);


        }

        [HttpPost]
        public async Task<IActionResult> AddOrder1(Order order)
        {
            ViewBag.status = "";
            /*            if (Request.Form.Files.Count > 0)
                        {
                            MemoryStream ms = new MemoryStream();
                            Request.Form.Files[0].CopyTo(ms);
                            Orderv.ImgPoster = ms.ToArray();
                        }*/
            //using grabage collection only for inbuilt classes
            using (HttpClient client = new HttpClient())
            {
                var foodcost = Convert.ToInt32(TempData["foodcost1"]);
                TempData.Keep();
                order.OrderTotal = order.Quantity * foodcost;
                order.OrderStatus = false;

                TempData["halltableuserid"] = order.HallTableId;
                TempData.Keep();


                orders.Add(order);
                TempData["status"] = true;
                while (Convert.ToBoolean(TempData["status"]))
                {
                    TempData.Keep();
                    return RedirectToAction("Index", "Order");
                }
                foreach (var item in orders)
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(orders), Encoding.UTF8, "application/json");
                    string endPoint = _configuration["WebApiBaseUrl"] + "Order/AddOrder";//api controller name and its function

                    using (var response = await client.PostAsync(endPoint, content))
                    {
                        if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        {   //dynamic viewbag we can create any variable name in run time
                            ViewBag.status = "Ok";
                            ViewBag.message = "Order " + item.OrderId + " Added Successfull!!";
                        }

                        else
                        {
                            ViewBag.status = "Error";
                            ViewBag.message = "Wrong Entries";
                        }

                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> ConfirmOrder()
        {
            TempData["status"] = false;
            TempData.Keep();
            using (HttpClient client = new HttpClient())
            {
                int count = 0;
                foreach (var item in orders)
                {   
                    StringContent content = new StringContent(JsonConvert.SerializeObject(item), Encoding.UTF8, "application/json");
                    string endPoint = _configuration["WebApiBaseUrl"] + "Order/AddOrder";//api controller name and its function
                    count++;
                    using (var response = await client.PostAsync(endPoint, content))
                    {
                        if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        {   //dynamic viewbag we can create any variable name in run time
                            ViewBag.status = "Ok";
                            ViewBag.message = count + "Order  Added Successfull!!";
                        }

                        else
                        {
                            ViewBag.status = "Error";
                            ViewBag.message = "Wrong Entries";
                        }

                    }

                }
                return View();
            }
           
        }


        [HttpGet]

        public async Task<IActionResult> GetAllFoods(Food food)
        {
            IEnumerable<Food> foodresult = null;
            using (HttpClient client = new HttpClient())
            {


                string endPoint = _configuration["WebApiBaseUrl"] + "Food/GetFoods";//api controller name and httppost name given inside httppost in moviecontroller of api

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {   //dynamic viewbag we can create any variable name in run time
                        var result = await response.Content.ReadAsStringAsync();
                        foodresult = JsonConvert.DeserializeObject<IEnumerable<Food>>(result);
                    }



                }
            }
            return View(foodresult);
        }

        [HttpGet]

        public IActionResult GetOrders1()
        {

            return View(orders);
        }

        public async Task<IActionResult> CancelOrder(int HallId)
        {

            IEnumerable<Order> orderresult = null;
            using (HttpClient client = new HttpClient())
            {


                string endPoint = _configuration["WebApiBaseUrl"] + "Order/GetOrdersByHallById?HallId=" + HallId;//api controller name and httppost name given inside httppost in moviecontroller of api

                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {   //dynamic viewbag we can create any variable name in run time
                        var result = await response.Content.ReadAsStringAsync();
                        orderresult = JsonConvert.DeserializeObject<IEnumerable<Order>>(result);
                    }

                    if(orderresult==null)
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "You have Not Ordered Anything";
                    }


                }
            }


            foreach (var item in orderresult)
            {
                ViewBag.status = "";
                //using grabage collection only for inbuilt classes
                using (HttpClient client = new HttpClient())
                {

                    string endPoint = _configuration["WebApiBaseUrl"] + "Order/DeleteOrder?orderId=" + item.OrderId;  //api controller name and its function

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Views/Order/AddOrder1.cshtml
@{
    ViewData["Title"] = "AddOrder";
}

<h1>AddOrder</h1>

@model RestaurantEntity.Order


<div>
    <a asp-controller="Customer" asp-action="Index">Index</a>
    <hr />
</div>
<form method="post" enctype="multipart/form-data">
    <h2>Add Order </h2>
    <div class="form-group">
        @*  form group for automatic audjustment for various screen sizes*@
        <label>Order Quantity</label>
        <input type="number" asp-for="Quantity" min="0" max="10" class="form-control" placeholder="Enter Order quantity" />
    </div>
    <div class="form-group">
        <label>Order Time</label>
        <input type="datetime-local" asp-for="OrderDate" class="form-control" placeholder="Enter Order Time" required />
    </div>
    <div class="form-group">
        <label>Food Id</label>
        <input type="text" asp-for="FoodId" class="form-control" placeholder="Enter Food ID" required />
    </div>
    <div class="form-group">
        <label>Hall Table Id</label>
        <select asp-for="HallTableId" asp-items="@ViewBag.tablelist" class="form-control" placeholder="Select Hall Table ID" required></select>
  
    </div>
   


    @* <div class="form-group">
    <label>Order Poster</label>
    <input type="file" id="poster" name="poster" class="form-control" required />
    </div>
    *@ 
   
    <input type="submit" value="Save" class="btn btn-success" />
     @*submit display message for required option required works only with submit*@
    <input type="button" value="Reset" class="btn btn-outline-secondary" />

    <hr />
    @*submit sends form to server thats why we use submit not button type  *@
    @*   by default get request is called so we have mention post in the initial stage of form which will call httppost in Ordercontroller *@
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

    

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Views/Order/CancelOrder.cshtml
@{
    ViewData["Title"] = "CancelOrder";
}

@if (ViewBag.status == "Ok")
{
    <div class="alert alert-success">
        @ViewBag.message
    </div>
}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">
        @ViewBag.message
    </div>
}

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Views/Order/ConfirmOrder.cshtml
@{
    ViewData["Title"] = "ConfirmOrder";
}


@if (ViewBag.status == "Ok")
{
    <div class="alert alert-success">
        @ViewBag.message
    </div>
}

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Views/Order/GetOrders1.cshtml
@model IEnumerable<RestaurantEntity.Order>
    @{
        ViewData["Title"] = "ConfirmOrder";
    }

    <h1>ConfirmOrder</h1>
    <div class="row">
        <div class="col-12">
            <h3>Orders</h3>
            <hr />
            <table class="table table-light table-bordered table-hover">
                <thead>
                    <tr>
                        
                        <th>Order Quantity</th>
                        <th>Order OrderTotal</th>
                       
                        <th>Order FoodId</th>
                        <th>Order Date</th>
                        

                  
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                {
                    <a asp-controller="Order" asp-action="ConfirmOrder" class="btn btn-success">Confirm Order</a>
                    <tr>&nbsp;</tr>
                    <a asp-controller="Order" asp-action="ViewOrdered" asp-route-HallId="@item.HallTableId" class="btn btn-success">View Ordered</a>
                    <tr>&nbsp;</tr>
                 
                   
                    <a asp-controller="Order" asp-action="CancelOrder" asp-route-HallId="@item.HallTableId" class="btn btn-danger">Cancel All Order</a>
                    <tr>&nbsp;</tr>
                    <a asp-controller="Bill" asp-action="GetBill" class="btn btn-outline-success">Get Bill</a>



                    break;
                }

                    @foreach (var Order in Model) @*mvc controller name is asp controller and its function name is asp-action and asp-route-moveid (is used in url means ) we need pass the same argument in  editOrder of Ordercontroller (route name) here which is OrderId
                    which can be written as http://localhost:32344/Orders/edit Order?Orderid=2//
                    *@
                    {
                        @* string imageBase64Data = Convert.ToBase64String(Order.ImgPoster);
                    string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);*@
                        <tr>
                         
                            <td>@Order.Quantity</td>
                            <td>@Order.OrderTotal</td>
                            
                            <td>@Order.FoodId</td>
                            <td>@Order.HallTableId</td>
                            <td>@Order.OrderDate</td>
                     
                         

                        </tr>

                    }
                  
                </tbody>
            </table>
        </div>
    </div>

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Views/Order/Index.cshtml
@model IEnumerable<RestaurantEntity.Food>

<body style="background-color:black">

    <div >

        <h2 class="text-light text-center">Foods  <p class="text-right text-light"><a asp-controller="Order" asp-action="GetOrders1" class="btn btn-primary ">View List</a></p></h2>
        <br/>

      
     
        
              
                <div class=" row">
                    
                      @foreach (var food in Model)
                    {
                        string imageBase64Data = Convert.ToBase64String(food.FoodImage);
                        string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);

                        <div class="col-md-3">

                            <div class="col-md-3">
                                <div class="card" style="width: 15rem;">
                                    <div class="bg-image hover-overlay ripple shadow-1-strong rounded"
                                     data-mdb-ripple-color="light">
                                        <img height="150" src="@imageDataURL" class="card-img-top" alt="...">
                                        <div class="card-body">
                                            <h5 class="card-title">@food.FoodName</h5>
                                            <p class="card-text">Type(Veg/NonVeg):@food.FoodType &nbsp;&nbsp;&nbsp;&nbsp; Food Cusine: @food.FoodCuisine</p>

                                            <p class="card-text">Cost:₹@food.FoodCost</p>
                
                                          <a asp-controller="Order" asp-action="AddOrder1"asp-route-FoodId="@food.FoodId" type="button" class="btn btn-success">Add to Cart</a>
         
                                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br/>
                        </div>


                    }
                    
                </div>

</div>
           </body>  


       

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Views/Order/UpdateOrder1.cshtml
@model RestaurantEntity.Order
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<h1>Edit Order</h1>

<form method="post" enctype="multipart/form-data">

    <div class="form-group">
        @*  form group for automatic audjustment for various screen sizes*@
        <label>Order Id</label>
        <input type="text" asp-for="OrderId" class="form-control" placeholder="Enter Order Id" required />
    </div>
    <div class="form-group">
        @*  form group for automatic audjustment for various screen sizes*@
        <label>Order Quantity</label>
        <input type="text" asp-for="Quantity" class="form-control" placeholder="Enter Order Quantity" required />
    </div>
    <div class="form-group"  hidden>
        <label>Food Id</label>
        <input type="text" asp-for="FoodId" class="form-control" placeholder="Enter Food Id" required  />
    </div>
    <div class="form-group" hidden>
        <label>Hall table Id</label>
        <input type="text" asp-for="HallTableId" class="form-control" placeholder="Enter Hall table Id" required />
    </div>

    <div class="form-group" hidden>
        <label>Hall table Id</label>
        <input type="datetime" asp-for="OrderDate" class="form-control" placeholder="Enter Order Date" required />
    </div>

  

    @* <div class="form-group">
    <label>Order Poster</label>
    <input type="file" id="poster" name="poster" class="form-control" required />
    </div>*@

    <input type="submit" value="Save" class="btn btn-outline-success" /> @*submit display message for required option required works only with submit*@
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @*submit sends form to server thats why we use submit not button type  *@
    @*   by default get request is called so we have mention post in the initial stage of form which will call httppost in Ordercontroller *@
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

Restaurant_Nov_11-main/RestaurantManagement/RestaurantMVCUI/Views/Order/ViewOrdered.cshtml
@model IEnumerable<RestaurantEntity.Order>
@{
    ViewData["Title"] = "ViewOrdered";
}

<h1>ViewOrdered</h1>




    <div class="row">
        <div class="col-12">
            <h3>Orders</h3>
            <hr />
            <table class="table table-light table-bordered table-hover">
                <thead>
                    <tr>
                        
                        <th>Order Quantity</th>-
                        <th>Order OrderTotal</th>
                       
                        <th>Order FoodId</th>
                        <th>Order Date</th>


                  
                    </tr>
                </thead>
                <tbody>
                    @foreach (var Order in Model) @*mvc controller name is asp controller and its function name is asp-action and asp-route-moveid (is used in url means ) we need pass the same argument in  editOrder of Ordercontroller (route name) here which is OrderId
                    which can be written as http://localhost:32344/Orders/edit Order?Orderid=2//
                    *@
                    {
                        @* string imageBase64Data = Convert.ToBase64String(Order.ImgPoster);
                    string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);*@
                        <tr>
                         
                            <td>@Order.Quantity</td>
                            <td>@Order.OrderTotal</td>
                            
                            <td>@Order.FoodId</td>
                            <td>@Order.HallTableId</td>
                            <td>@Order.OrderDate</td>
                        <td><a asp-controller="Order" asp-action="UpdateOrder1" asp-route-OrderId="@Order.OrderId" class="btn btn-success">Update Order</a></td>
                        </tr>

                    }
                  
                </tbody>
            </table>
        </div>
    </div>